server:
  port: 8761

spring:
  security:
    basic:
      enabled: true
    user:
      name: "guest"
      password: "s3cr3t"
   
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    preferIpAddress: true  