server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://guest:s3cr3t@127.0.0.1:8761/eureka
      
spring:
  datasource:
    username: 'guest'
    password: 's3cr3t'
    url: jdbc:mysql://127.0.0.1:3306/productdb?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useUnicode=yes&characterEncoding=utf8
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect      