server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://guest:s3cr3t@127.0.0.1:8761/eureka
      
spring:
  datasource:
    username: 'guest'
    password: 's3cr3t'
    url: jdbc:mysql://127.0.0.1:3306/uaadb
  jpa:
    database: myslq
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true 